name: "Argo Tunnel"

inputs:
  ARGO_TUNNEL_NAME:
    description: "name of your argo tunnel"
    required: true
  ARGO_TUNNEL_TOKEN:
    description: "credential files of your argo tunnel"
    required: true
  ARGO_VERSION:
    description: "version tags of argo release"
    required: false
    defailt: "2021.5.10"
  XRAY_VLESS_UUID:
    description: "uuid for your VLESS connection"
    required: true
  XRAY_GRPC_SERVICENAME:
    description: "service name for your grpc connection"
    required: true
  XRAY_TLS_CERT:
    description: "tls cert for your grpc connection"
    required: true
  XRAY_TLS_KEY:
    description: "tls private key for your grpc connection"
    required: true
  XRAY_VERSION:
    description: "version tag of xray-core release"
    required: false
    defailt: "v1.4.2"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ARGO_TUNNEL_NAME }}
    - ${{ inputs.ARGO_VERSION }}
    - ${{ inputs.XRAY_VLESS_UUID }}
    - ${{ inputs.XRAY_XRAY_TLS_CERT }}
    - ${{ inputs.XRAY_XRAY_TLS_KEY }}
    - ${{ inputs.XRAY_GRPC_SERVICENAME }}
    - ${{ inputs.XRAY_VERSION }}